### ISSUE TITLE
Missing image on invite confirmation page?

### ISSUE THREAD

**Issue by jbarnicle** [18F/cg-uaa-extras#49]
![screen shot 2016-12-01 at 12 42 37 pm](https://cloud.githubusercontent.com/assets/737400/20807272/d95dafa6-b7c3-11e6-8ed4-219f6ed8699a.png)

on `fr.cloud.gov`
@rogeruiz @LinuxBozo

**Comment by rogeruiz** [comment]
Closed by #35
